/**
 * ISO 3166-1 alpha-2 country codes with display labels.
 * Stored value is the 2-letter ISO code (e.g. "US").
 * Label format: "(XX) Country Name"
 */
export interface Country {
  value: string;
  label: string;
}

export const COUNTRIES: Country[] = [
  { value: 'AF', label: '(AF) Afghanistan' },
  { value: 'AL', label: '(AL) Albania' },
  { value: 'DZ', label: '(DZ) Algeria' },
  { value: 'AD', label: '(AD) Andorra' },
  { value: 'AO', label: '(AO) Angola' },
  { value: 'AG', label: '(AG) Antigua and Barbuda' },
  { value: 'AR', label: '(AR) Argentina' },
  { value: 'AM', label: '(AM) Armenia' },
  { value: 'AU', label: '(AU) Australia' },
  { value: 'AT', label: '(AT) Austria' },
  { value: 'AZ', label: '(AZ) Azerbaijan' },
  { value: 'BS', label: '(BS) Bahamas' },
  { value: 'BH', label: '(BH) Bahrain' },
  { value: 'BD', label: '(BD) Bangladesh' },
  { value: 'BB', label: '(BB) Barbados' },
  { value: 'BY', label: '(BY) Belarus' },
  { value: 'BE', label: '(BE) Belgium' },
  { value: 'BZ', label: '(BZ) Belize' },
  { value: 'BJ', label: '(BJ) Benin' },
  { value: 'BT', label: '(BT) Bhutan' },
  { value: 'BO', label: '(BO) Bolivia' },
  { value: 'BA', label: '(BA) Bosnia and Herzegovina' },
  { value: 'BW', label: '(BW) Botswana' },
  { value: 'BR', label: '(BR) Brazil' },
  { value: 'BN', label: '(BN) Brunei' },
  { value: 'BG', label: '(BG) Bulgaria' },
  { value: 'BF', label: '(BF) Burkina Faso' },
  { value: 'BI', label: '(BI) Burundi' },
  { value: 'CV', label: '(CV) Cabo Verde' },
  { value: 'KH', label: '(KH) Cambodia' },
  { value: 'CM', label: '(CM) Cameroon' },
  { value: 'CA', label: '(CA) Canada' },
  { value: 'CF', label: '(CF) Central African Republic' },
  { value: 'TD', label: '(TD) Chad' },
  { value: 'CL', label: '(CL) Chile' },
  { value: 'CN', label: '(CN) China' },
  { value: 'CO', label: '(CO) Colombia' },
  { value: 'KM', label: '(KM) Comoros' },
  { value: 'CD', label: '(CD) Congo (DRC)' },
  { value: 'CG', label: '(CG) Congo (Republic)' },
  { value: 'CR', label: '(CR) Costa Rica' },
  { value: 'CI', label: "(CI) Côte d'Ivoire" },
  { value: 'HR', label: '(HR) Croatia' },
  { value: 'CU', label: '(CU) Cuba' },
  { value: 'CY', label: '(CY) Cyprus' },
  { value: 'CZ', label: '(CZ) Czech Republic' },
  { value: 'DK', label: '(DK) Denmark' },
  { value: 'DJ', label: '(DJ) Djibouti' },
  { value: 'DM', label: '(DM) Dominica' },
  { value: 'DO', label: '(DO) Dominican Republic' },
  { value: 'EC', label: '(EC) Ecuador' },
  { value: 'EG', label: '(EG) Egypt' },
  { value: 'SV', label: '(SV) El Salvador' },
  { value: 'GQ', label: '(GQ) Equatorial Guinea' },
  { value: 'ER', label: '(ER) Eritrea' },
  { value: 'EE', label: '(EE) Estonia' },
  { value: 'SZ', label: '(SZ) Eswatini' },
  { value: 'ET', label: '(ET) Ethiopia' },
  { value: 'FJ', label: '(FJ) Fiji' },
  { value: 'FI', label: '(FI) Finland' },
  { value: 'FR', label: '(FR) France' },
  { value: 'GA', label: '(GA) Gabon' },
  { value: 'GM', label: '(GM) Gambia' },
  { value: 'GE', label: '(GE) Georgia' },
  { value: 'DE', label: '(DE) Germany' },
  { value: 'GH', label: '(GH) Ghana' },
  { value: 'GR', label: '(GR) Greece' },
  { value: 'GD', label: '(GD) Grenada' },
  { value: 'GT', label: '(GT) Guatemala' },
  { value: 'GN', label: '(GN) Guinea' },
  { value: 'GW', label: '(GW) Guinea-Bissau' },
  { value: 'GY', label: '(GY) Guyana' },
  { value: 'HT', label: '(HT) Haiti' },
  { value: 'HN', label: '(HN) Honduras' },
  { value: 'HU', label: '(HU) Hungary' },
  { value: 'IS', label: '(IS) Iceland' },
  { value: 'IN', label: '(IN) India' },
  { value: 'ID', label: '(ID) Indonesia' },
  { value: 'IR', label: '(IR) Iran' },
  { value: 'IQ', label: '(IQ) Iraq' },
  { value: 'IE', label: '(IE) Ireland' },
  { value: 'IL', label: '(IL) Israel' },
  { value: 'IT', label: '(IT) Italy' },
  { value: 'JM', label: '(JM) Jamaica' },
  { value: 'JP', label: '(JP) Japan' },
  { value: 'JO', label: '(JO) Jordan' },
  { value: 'KZ', label: '(KZ) Kazakhstan' },
  { value: 'KE', label: '(KE) Kenya' },
  { value: 'KI', label: '(KI) Kiribati' },
  { value: 'KW', label: '(KW) Kuwait' },
  { value: 'KG', label: '(KG) Kyrgyzstan' },
  { value: 'LA', label: '(LA) Laos' },
  { value: 'LV', label: '(LV) Latvia' },
  { value: 'LB', label: '(LB) Lebanon' },
  { value: 'LS', label: '(LS) Lesotho' },
  { value: 'LR', label: '(LR) Liberia' },
  { value: 'LY', label: '(LY) Libya' },
  { value: 'LI', label: '(LI) Liechtenstein' },
  { value: 'LT', label: '(LT) Lithuania' },
  { value: 'LU', label: '(LU) Luxembourg' },
  { value: 'MG', label: '(MG) Madagascar' },
  { value: 'MW', label: '(MW) Malawi' },
  { value: 'MY', label: '(MY) Malaysia' },
  { value: 'MV', label: '(MV) Maldives' },
  { value: 'ML', label: '(ML) Mali' },
  { value: 'MT', label: '(MT) Malta' },
  { value: 'MH', label: '(MH) Marshall Islands' },
  { value: 'MR', label: '(MR) Mauritania' },
  { value: 'MU', label: '(MU) Mauritius' },
  { value: 'MX', label: '(MX) Mexico' },
  { value: 'FM', label: '(FM) Micronesia' },
  { value: 'MD', label: '(MD) Moldova' },
  { value: 'MC', label: '(MC) Monaco' },
  { value: 'MN', label: '(MN) Mongolia' },
  { value: 'ME', label: '(ME) Montenegro' },
  { value: 'MA', label: '(MA) Morocco' },
  { value: 'MZ', label: '(MZ) Mozambique' },
  { value: 'MM', label: '(MM) Myanmar' },
  { value: 'NA', label: '(NA) Namibia' },
  { value: 'NR', label: '(NR) Nauru' },
  { value: 'NP', label: '(NP) Nepal' },
  { value: 'NL', label: '(NL) Netherlands' },
  { value: 'NZ', label: '(NZ) New Zealand' },
  { value: 'NI', label: '(NI) Nicaragua' },
  { value: 'NE', label: '(NE) Niger' },
  { value: 'NG', label: '(NG) Nigeria' },
  { value: 'KP', label: '(KP) North Korea' },
  { value: 'MK', label: '(MK) North Macedonia' },
  { value: 'NO', label: '(NO) Norway' },
  { value: 'OM', label: '(OM) Oman' },
  { value: 'PK', label: '(PK) Pakistan' },
  { value: 'PW', label: '(PW) Palau' },
  { value: 'PA', label: '(PA) Panama' },
  { value: 'PG', label: '(PG) Papua New Guinea' },
  { value: 'PY', label: '(PY) Paraguay' },
  { value: 'PE', label: '(PE) Peru' },
  { value: 'PH', label: '(PH) Philippines' },
  { value: 'PL', label: '(PL) Poland' },
  { value: 'PT', label: '(PT) Portugal' },
  { value: 'QA', label: '(QA) Qatar' },
  { value: 'RO', label: '(RO) Romania' },
  { value: 'RU', label: '(RU) Russia' },
  { value: 'RW', label: '(RW) Rwanda' },
  { value: 'KN', label: '(KN) Saint Kitts and Nevis' },
  { value: 'LC', label: '(LC) Saint Lucia' },
  { value: 'VC', label: '(VC) Saint Vincent and the Grenadines' },
  { value: 'WS', label: '(WS) Samoa' },
  { value: 'SM', label: '(SM) San Marino' },
  { value: 'ST', label: '(ST) São Tomé and Príncipe' },
  { value: 'SA', label: '(SA) Saudi Arabia' },
  { value: 'SN', label: '(SN) Senegal' },
  { value: 'RS', label: '(RS) Serbia' },
  { value: 'SC', label: '(SC) Seychelles' },
  { value: 'SL', label: '(SL) Sierra Leone' },
  { value: 'SG', label: '(SG) Singapore' },
  { value: 'SK', label: '(SK) Slovakia' },
  { value: 'SI', label: '(SI) Slovenia' },
  { value: 'SB', label: '(SB) Solomon Islands' },
  { value: 'SO', label: '(SO) Somalia' },
  { value: 'ZA', label: '(ZA) South Africa' },
  { value: 'SS', label: '(SS) South Sudan' },
  { value: 'ES', label: '(ES) Spain' },
  { value: 'LK', label: '(LK) Sri Lanka' },
  { value: 'SD', label: '(SD) Sudan' },
  { value: 'SR', label: '(SR) Suriname' },
  { value: 'SE', label: '(SE) Sweden' },
  { value: 'CH', label: '(CH) Switzerland' },
  { value: 'SY', label: '(SY) Syria' },
  { value: 'TW', label: '(TW) Taiwan' },
  { value: 'TJ', label: '(TJ) Tajikistan' },
  { value: 'TZ', label: '(TZ) Tanzania' },
  { value: 'TH', label: '(TH) Thailand' },
  { value: 'TL', label: '(TL) Timor-Leste' },
  { value: 'TG', label: '(TG) Togo' },
  { value: 'TO', label: '(TO) Tonga' },
  { value: 'TT', label: '(TT) Trinidad and Tobago' },
  { value: 'TN', label: '(TN) Tunisia' },
  { value: 'TR', label: '(TR) Turkey' },
  { value: 'TM', label: '(TM) Turkmenistan' },
  { value: 'TV', label: '(TV) Tuvalu' },
  { value: 'UG', label: '(UG) Uganda' },
  { value: 'UA', label: '(UA) Ukraine' },
  { value: 'AE', label: '(AE) United Arab Emirates' },
  { value: 'GB', label: '(GB) United Kingdom' },
  { value: 'US', label: '(US) United States' },
  { value: 'UY', label: '(UY) Uruguay' },
  { value: 'UZ', label: '(UZ) Uzbekistan' },
  { value: 'VU', label: '(VU) Vanuatu' },
  { value: 'VE', label: '(VE) Venezuela' },
  { value: 'VN', label: '(VN) Vietnam' },
  { value: 'YE', label: '(YE) Yemen' },
  { value: 'ZM', label: '(ZM) Zambia' },
  { value: 'ZW', label: '(ZW) Zimbabwe' },
];
