/**
 * Generates the 36 (12 hue × 3 mood) dark theme palettes, plus a swatch
 * table for the picker UI, from a single OKLCH model. Also asserts WCAG 2.1
 * contrast on every generated palette so a bad constant fails the build
 * instead of shipping an unreadable theme.
 *
 * The model (mood-invariant lightness ladder, chroma-only mood axis, the
 * anti-mud hue/chroma corrections for the amber/orange/lime band, and the
 * per-hue accent table) is specified in the approved theming plan's
 * "Palette generation" section — every numeric constant below is transcribed
 * from there, not re-derived.
 *
 * Hue/mood tables here are intentionally script-local: they exist only to
 * drive this generator and are not the shared theme-identity constants
 * (`packages/shared/src/constants/themes.ts`), which are hand-written and
 * authoritative for `ThemeKey`/`ThemeHue`/`ThemeMood`.
 *
 * `culori` is a build-time-only devDependency — the generated CSS/TS files
 * are committed, and nothing at runtime imports this script or `culori`.
 *
 * `--border` on `--card` is asserted against a 1.35:1 *floor* only, not the
 * usual 3:1 non-text-contrast guidance. The design deliberately uses hairline
 * dividers, not high-contrast outlines — today's three hand-written themes
 * measure 1.43–1.77:1 there. Raising it would be a redesign, not a fix; the
 * floor only guards against a future parameter change making borders vanish
 * entirely.
 *
 * Run:
 *   pnpm --filter @my-hub/hub gen:palettes         generate + assert, write files
 *   pnpm --filter @my-hub/hub gen:palettes:report  print the full ratio matrix, never throws
 *   pnpm --filter @my-hub/hub gen:palettes:check   generate, then `git diff --exit-code` the outputs
 */
import { writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

import { clampChroma, formatHex, oklch, rgb, wcagContrast } from 'culori';
import type { Oklch, Rgb } from 'culori';
import { format as prettierFormat, resolveConfig } from 'prettier';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const CSS_OUT = path.resolve(__dirname, '../src/styles/themes.generated.css');
const SWATCH_OUT = path.resolve(__dirname, '../src/lib/theme-swatches.generated.ts');
const GENERATED_HEADER = `/* GENERATED by scripts/gen-palettes.mts — do not edit. Run: pnpm --filter @my-hub/hub gen:palettes */`;

const REPORT_MODE = process.argv.includes('--report');

// ---------------------------------------------------------------------------
// Model constants — transcribed verbatim from the plan's "Palette generation"
// section. Do not "improve" these without re-checking the worked examples.
// ---------------------------------------------------------------------------

/** Mood-invariant surface lightness ladder. Guarantees contrast across all 36 palettes. */
const LADDER = {
  bg: 0.152,
  shell: 0.178,
  card: 0.21,
  card2: 0.245,
  card3: 0.283,
  border: 0.36,
} as const;

type SurfaceToken = keyof typeof LADDER;
const SURFACE_TOKENS = Object.keys(LADDER) as SurfaceToken[];

const TEXT_L = { text: 0.965, muted: 0.7, subtle: 0.568 } as const;
type TextToken = keyof typeof TEXT_L;
const TEXT_TOKENS = Object.keys(TEXT_L) as TextToken[];

/**
 * Text-token chroma is `min(mul * Cbase, cap)`, where
 * `Cbase = Cs0[mood] * surfaceChromaMul(H)`. Refitted against the three
 * hand-written originals (travel/finances/calories) — the initial 0.25x/
 * 1.6x/1.4x fractions were ~2.5x too low and produced near-neutral grey
 * secondary text, losing the hue tint that gives e.g. Finances' violet-grey
 * `--muted` its character. The caps exist so a `deep` cool hue (Cs0 0.04)
 * doesn't produce garishly saturated blue-grey body text.
 */
const TEXT_CHROMA_MUL: Record<TextToken, number> = { text: 1.0, muted: 3.7, subtle: 3.1 };
const TEXT_CHROMA_CAP: Record<TextToken, number> = { text: 0.024, muted: 0.105, subtle: 0.088 };

const OVERLAY_L = 0.128;
const OVERLAY_ALPHA = 0.7;

/** Mood is a chroma axis only — surface shape multipliers, applied on top of Cs0[mood]. */
const SHAPE: Record<SurfaceToken, number> = {
  bg: 1.0,
  shell: 1.15,
  card: 1.4,
  card2: 1.7,
  card3: 2.0,
  border: 2.85,
};

const CS0 = { soft: 0.016, classic: 0.024, deep: 0.04 } as const;

const MOOD = {
  soft: { accL: 0.73, k: 0.92, Ccap: 0.15 },
  classic: { accL: 0.7, k: 0.96, Ccap: 0.165 },
  deep: { accL: 0.655, k: 0.99, Ccap: 0.195 },
} as const;

type MoodKey = keyof typeof MOOD;
const MOOD_KEYS = Object.keys(MOOD) as MoodKey[];

/**
 * Slate is a chromaless accent at L 0.70 (`#a6a6a6`), which reads as
 * *disabled* rather than as a color choice. It bypasses the chroma-fraction
 * formula entirely and uses fixed absolute chroma per mood instead
 * (graphite → steel → ink).
 */
const SLATE_ACCENT_C = { soft: 0.045, classic: 0.055, deep: 0.07 } as const;
const SLATE_SURFACE_C0 = { soft: 0.004, classic: 0.006, deep: 0.01 } as const;
/** Extra dampener so slate's text tokens don't out-chroma its near-neutral surfaces. */
const SLATE_TEXT_MUL = 0.4;

interface HueDef {
  H: number;
  Lo: number;
  /** `'special'` marks slate, which is handled separately throughout. */
  kMul: number | 'special';
}

/**
 * The 12 accent hues. `Lo` compensates for blues reading darker and
 * yellow/lime reading lighter than their L implies; `kMul` trims hues (red,
 * magenta) whose sRGB gamut is so large that `k * Cmax` would go neon.
 */
const HUES: Record<string, HueDef> = {
  emerald: { H: 162, Lo: 0.0, kMul: 1.0 },
  lime: { H: 132, Lo: -0.03, kMul: 0.9 },
  amber: { H: 82, Lo: -0.02, kMul: 1.0 },
  orange: { H: 50, Lo: 0.0, kMul: 1.0 },
  rose: { H: 4, Lo: 0.0, kMul: 0.8 },
  fuchsia: { H: 322, Lo: 0.0, kMul: 0.7 },
  violet: { H: 293, Lo: 0.005, kMul: 1.0 },
  indigo: { H: 274, Lo: 0.02, kMul: 1.0 },
  ocean: { H: 250, Lo: 0.025, kMul: 1.0 },
  sky: { H: 228, Lo: 0.015, kMul: 1.0 },
  teal: { H: 192, Lo: 0.005, kMul: 1.0 },
  slate: { H: 250, Lo: 0.025, kMul: 'special' },
};

const HUE_KEYS = Object.keys(HUES);

/**
 * Anti-mud correction. Calories' bug was a hue-drift, not a saturation bug:
 * its accent sits at H≈48 but its surfaces drifted to H 67–80, which at low
 * L *is* olive-brown. This pulls amber/orange/lime surface (and text) hues
 * back toward ember/cocoa and dampens their chroma.
 */
function surfaceHue(H: number): number {
  return H >= 35 && H <= 115 ? 30 + 0.35 * (H - 30) : H;
}
function surfaceChromaMul(H: number): number {
  if (H >= 35 && H <= 115) return 0.55; // amber/orange: brown is unavoidable, use less
  if (H > 115 && H <= 145) return 0.75; // lime: olive risk
  return 1.0;
}

// ---------------------------------------------------------------------------
// Color helpers
// ---------------------------------------------------------------------------

function mkOklch(l: number, c: number, h: number): Oklch {
  return { mode: 'oklch', l, c, h };
}

/**
 * Gamut-map by reducing chroma at fixed L/H — we must never let culori's
 * default RGB channel clipping run, or the lightness ladder (and therefore
 * contrast) would not survive the trip to sRGB.
 */
function toHex(o: Oklch): string {
  const clamped = clampChroma(o, 'oklch') as Oklch;
  return formatHex(clamped);
}

function toRgbChannels(hex: string): { r: number; g: number; b: number } {
  const c = rgb(hex) as Rgb;
  return { r: Math.round(c.r * 255), g: Math.round(c.g * 255), b: Math.round(c.b * 255) };
}

function toRgba(hex: string, alpha: number): string {
  const { r, g, b } = toRgbChannels(hex);
  return `rgba(${r}, ${g}, ${b}, ${alpha})`;
}

/** sRGB gamut boundary chroma at fixed L, H — found by gamut-mapping a saturated seed down. */
function cmax(l: number, h: number): number {
  const clamped = clampChroma(mkOklch(l, 0.5, h), 'oklch') as Oklch;
  return clamped.c;
}

function hueDist(a: number, b: number): number {
  const d = Math.abs(a - b) % 360;
  return d > 180 ? 360 - d : d;
}

// ---------------------------------------------------------------------------
// Accent
// ---------------------------------------------------------------------------

interface Accent {
  hex: string;
  l: number;
  c: number;
  h: number;
}

function computeAccent(hueKey: string, moodKey: MoodKey): Accent {
  const hue = HUES[hueKey];
  const mood = MOOD[moodKey];
  const l = mood.accL + hue.Lo;
  const c =
    hueKey === 'slate' ? SLATE_ACCENT_C[moodKey] : Math.min(mood.k * (hue.kMul as number) * cmax(l, hue.H), mood.Ccap);
  return { hex: toHex(mkOklch(l, c, hue.H)), l, c, h: hue.H };
}

/**
 * Walks L downward from 0.24 in 0.005 steps at a chroma capped from the
 * accent's own chroma, taking the FIRST (lightest) tint that clears 4.5:1
 * against the accent. Falls back to whichever of white/black scores higher
 * only if nothing in the walk clears the threshold.
 */
function computeOnAccent(accent: Accent): string {
  const chroma = Math.min(0.3 * accent.c, 0.07);
  const steps = Math.round(0.24 / 0.005);
  for (let i = 0; i <= steps; i++) {
    const l = 0.24 - i * 0.005;
    const hex = toHex(mkOklch(l, chroma, accent.h));
    if (wcagContrast(hex, accent.hex) >= 4.5) return hex;
  }
  const white = '#ffffff';
  const black = '#000000';
  return wcagContrast(white, accent.hex) >= wcagContrast(black, accent.hex) ? white : black;
}

// ---------------------------------------------------------------------------
// Surfaces, overlay, text
// ---------------------------------------------------------------------------

function computeSurfaceHue(hueKey: string): number {
  const hue = HUES[hueKey];
  return hueKey === 'slate' ? hue.H : surfaceHue(hue.H);
}

function computeSurfaceChroma(hueKey: string, moodKey: MoodKey, shape: number): number {
  if (hueKey === 'slate') return SLATE_SURFACE_C0[moodKey] * shape;
  const hue = HUES[hueKey];
  return CS0[moodKey] * shape * surfaceChromaMul(hue.H);
}

function computeSurfaces(hueKey: string, moodKey: MoodKey): Record<SurfaceToken, string> {
  const H = computeSurfaceHue(hueKey);
  const out = {} as Record<SurfaceToken, string>;
  for (const token of SURFACE_TOKENS) {
    const c = computeSurfaceChroma(hueKey, moodKey, SHAPE[token]);
    out[token] = toHex(mkOklch(LADDER[token], c, H));
  }
  return out;
}

function computeOverlay(hueKey: string, moodKey: MoodKey): string {
  const H = computeSurfaceHue(hueKey);
  const c = computeSurfaceChroma(hueKey, moodKey, SHAPE.bg);
  return toRgba(toHex(mkOklch(OVERLAY_L, c, H)), OVERLAY_ALPHA);
}

function computeTextTokens(hueKey: string, moodKey: MoodKey): Record<TextToken, string> {
  const H = computeSurfaceHue(hueKey);
  const hue = HUES[hueKey];
  const out = {} as Record<TextToken, string>;
  for (const token of TEXT_TOKENS) {
    const mul = TEXT_CHROMA_MUL[token];
    const cap = TEXT_CHROMA_CAP[token];
    const cBase = hueKey === 'slate' ? SLATE_SURFACE_C0[moodKey] : CS0[moodKey] * surfaceChromaMul(hue.H);
    const c = hueKey === 'slate' ? SLATE_TEXT_MUL * Math.min(mul * cBase, cap) : Math.min(mul * cBase, cap);
    out[token] = toHex(mkOklch(TEXT_L[token], c, H));
  }
  return out;
}

// ---------------------------------------------------------------------------
// Semantic tokens — frozen across all 40 presets, with one computed
// collision guard. Base values below are transcribed from the existing
// travel-emerald.css (the canonical, uncorrupted set — calories-orange.css's
// nudged --sky was a bug, not a variant to preserve).
// ---------------------------------------------------------------------------

const SEMANTIC_BASE = {
  green: '#6ee7b7',
  blue: '#93c5fd',
  amber: '#fcd34d',
  red: '#f87171',
  violet: '#c084fc',
  teal: '#2dd4bf',
  orange: '#fb923c',
  pink: '#f472b6',
  emerald: '#34d399',
  sky: '#60a5fa',
} as const;

type SemanticToken = keyof typeof SEMANTIC_BASE;
const SEMANTIC_TOKENS = Object.keys(SEMANTIC_BASE) as SemanticToken[];

/** Only tokens with a hand-written `-d` companion get one regenerated on promotion. */
const SEMANTIC_D_ALPHA: Partial<Record<SemanticToken, number>> = {
  green: 0.1,
  blue: 0.1,
  amber: 0.1,
  red: 0.1,
  violet: 0.12,
  teal: 0.1,
};

const SEMANTIC_PROMOTED: Record<SemanticToken, string> = {
  green: '#a7f3d0',
  blue: '#bfdbfe',
  amber: '#fde68a',
  red: '#fca5a5',
  violet: '#ddd6fe',
  teal: '#5eead4',
  orange: '#fdba74',
  pink: '#f9a8d4',
  emerald: '#a7f3d0',
  sky: '#7dd3fc',
};

const SEMANTIC_OKLCH: Record<SemanticToken, Oklch> = Object.fromEntries(
  SEMANTIC_TOKENS.map(token => [token, oklch(SEMANTIC_BASE[token]) as Oklch]),
) as Record<SemanticToken, Oklch>;

/**
 * Promotes a semantic token to its Tailwind-300 variant when it collides
 * with the accent (within 25° of hue AND 0.08 of lightness) — lighter, same
 * hue, same meaning, separated on the lightness axis instead of pulled
 * toward the collision.
 */
function computeSemantics(accent: Accent): Record<string, string> {
  const out: Record<string, string> = {};
  for (const token of SEMANTIC_TOKENS) {
    const base = SEMANTIC_OKLCH[token];
    const collides = hueDist(base.h ?? 0, accent.h) <= 25 && Math.abs(base.l - accent.l) <= 0.08;
    out[token] = collides ? SEMANTIC_PROMOTED[token] : SEMANTIC_BASE[token];
  }
  for (const [token, alpha] of Object.entries(SEMANTIC_D_ALPHA) as Array<[SemanticToken, number]>) {
    out[`${token}-d`] = toRgba(out[token], alpha);
  }
  return out;
}

// ---------------------------------------------------------------------------
// Palette assembly
// ---------------------------------------------------------------------------

interface Palette {
  key: string;
  className: string;
  tokens: Array<[string, string]>;
}

function buildPalette(hueKey: string, moodKey: MoodKey): Palette {
  const accent = computeAccent(hueKey, moodKey);
  const surfaces = computeSurfaces(hueKey, moodKey);
  const overlay = computeOverlay(hueKey, moodKey);
  const text = computeTextTokens(hueKey, moodKey);
  const onAccent = computeOnAccent(accent);
  const semantics = computeSemantics(accent);

  // Token order matches the existing hand-written theme files exactly.
  const tokens: Array<[string, string]> = [
    ['bg', surfaces.bg],
    ['overlay', overlay],
    ['shell', surfaces.shell],
    ['card', surfaces.card],
    ['card2', surfaces.card2],
    ['card3', surfaces.card3],
    ['border', surfaces.border],
    ['text', text.text],
    ['muted', text.muted],
    ['subtle', text.subtle],
    ['accent', accent.hex],
    ['accent-d', toRgba(accent.hex, 0.12)],
    ['accent-shadow', toRgba(accent.hex, 0.4)],
    ['accent-hover', toRgba(accent.hex, 0.75)],
    ['green', semantics.green],
    ['green-d', semantics['green-d']],
    ['blue', semantics.blue],
    ['blue-d', semantics['blue-d']],
    ['amber', semantics.amber],
    ['amber-d', semantics['amber-d']],
    ['red', semantics.red],
    ['red-d', semantics['red-d']],
    ['violet', semantics.violet],
    ['violet-d', semantics['violet-d']],
    ['teal', semantics.teal],
    ['teal-d', semantics['teal-d']],
    ['orange', semantics.orange],
    ['pink', semantics.pink],
    ['emerald', semantics.emerald],
    ['sky', semantics.sky],
    ['on-accent', onAccent],
    ['on-solid', '#ffffff'],
  ];

  return { key: `${hueKey}-${moodKey}`, className: `${hueKey}-${moodKey}-theme`, tokens };
}

// ---------------------------------------------------------------------------
// Contrast assertions
// ---------------------------------------------------------------------------

interface RatioResult {
  label: string;
  ratio: number;
  threshold: number;
  pass: boolean;
  /**
   * When false, a failure is surfaced in `--report` and in the console
   * summary but does not fail `gen:palettes`. Used only for the
   * white-on-semantic check below — see its comment.
   */
  fatal: boolean;
}

function checkRatio(label: string, fg: string, bg: string, threshold: number, out: RatioResult[], fatal = true): void {
  const ratio = wcagContrast(fg, bg);
  out.push({ label, ratio, threshold, pass: ratio >= threshold, fatal });
}

function computeContrastResults(t: Record<string, string>): RatioResult[] {
  const results: RatioResult[] = [];
  for (const surface of ['bg', 'card', 'card2', 'card3']) {
    checkRatio(`text on ${surface}`, t.text, t[surface], 4.5, results);
    checkRatio(`muted on ${surface}`, t.muted, t[surface], 4.5, results);
  }
  checkRatio('subtle on card3', t.subtle, t.card3, 3.0, results);
  checkRatio('accent on bg', t.accent, t.bg, 3.0, results);
  checkRatio('accent on card3', t.accent, t.card3, 3.0, results);
  checkRatio('on-accent on accent', t['on-accent'], t.accent, 4.5, results);
  // NON-FATAL, KNOWN FAILING: the semantic tokens are frozen Tailwind
  // 300/400 hexes (per plan) and are identical in all 36 palettes, so this
  // check's outcome does not depend on anything this generator computes.
  // Measured here (and unchanged since these hexes never vary): red 2.77,
  // violet 2.64, teal 1.86, blue 1.80, green 1.52, amber 1.44 — all below
  // 3:1, worst 1.44:1 (amber). Promotion to the even-lighter Tailwind-300
  // collision guard only makes this worse (down to 1.39-1.90:1), so no
  // per-palette tuning can fix it. Kept as a non-fatal, reported check
  // rather than silently dropped or silently "fixed" by hand-picking new
  // frozen hexes, which the plan explicitly forbids for this token set.
  // Flagged back to the plan owner; see this step's final report.
  for (const semantic of ['red', 'green', 'amber', 'blue', 'violet', 'teal']) {
    checkRatio(`white on ${semantic}`, '#ffffff', t[semantic], 3.0, results, false);
  }
  // Floor only — see the module doc comment on why this isn't 3:1.
  checkRatio('border on card', t.border, t.card, 1.35, results);
  return results;
}

// ---------------------------------------------------------------------------
// Emission
// ---------------------------------------------------------------------------

function renderCssBlock(className: string, tokens: Array<[string, string]>): string {
  const lines = tokens.map(([k, v]) => `  --${k}: ${v};`).join('\n');
  return `.${className} {\n${lines}\n}`;
}

async function writeGeneratedCss(blocks: string[]): Promise<void> {
  const raw = `${GENERATED_HEADER}\n\n${blocks.join('\n\n')}\n`;
  const config = (await resolveConfig(CSS_OUT)) ?? {};
  const formatted = await prettierFormat(raw, { ...config, filepath: CSS_OUT, parser: 'css' });
  await writeFile(CSS_OUT, formatted, 'utf8');
}

interface Swatch {
  accent: string;
  bg: string;
  card: string;
}

/** Read directly from the hand-written Signature CSS files — not re-derived. */
const SIGNATURE_SWATCHES: Record<string, Swatch> = {
  'graphite-signature': { accent: '#6366f1', bg: '#09090b', card: '#18181b' },
  'travel-signature': { accent: '#10b981', bg: '#030f0a', card: '#0a1e16' },
  'finances-signature': { accent: '#a78bfa', bg: '#0b0a14', card: '#171422' },
  'calories-signature': { accent: '#f97316', bg: '#110c05', card: '#221609' },
};

async function writeGeneratedSwatches(swatches: Record<string, Swatch>): Promise<void> {
  const entries = Object.entries(swatches)
    .map(([key, v]) => `  '${key}': { accent: '${v.accent}', bg: '${v.bg}', card: '${v.card}' },`)
    .join('\n');
  const raw = `${GENERATED_HEADER}\n\nexport const THEME_SWATCHES: Record<string, { accent: string; bg: string; card: string }> = {\n${entries}\n};\n`;
  const config = (await resolveConfig(SWATCH_OUT)) ?? {};
  const formatted = await prettierFormat(raw, { ...config, filepath: SWATCH_OUT, parser: 'typescript' });
  await writeFile(SWATCH_OUT, formatted, 'utf8');
}

// ---------------------------------------------------------------------------
// Report
// ---------------------------------------------------------------------------

interface ReportRow {
  key: string;
  label: string;
  ratio: number;
  threshold: number;
  fatal: boolean;
}

function printReport(rows: ReportRow[]): void {
  const grouped = new Map<string, ReportRow[]>();
  for (const row of rows) {
    const bucket = grouped.get(row.key);
    if (bucket) bucket.push(row);
    else grouped.set(row.key, [row]);
  }
  for (const [key, list] of grouped) {
    console.log(`\n${key}`);
    for (const row of list) {
      const pass = row.ratio >= row.threshold;
      const status = pass ? 'PASS' : row.fatal ? 'FAIL' : 'FAIL (waived)';
      console.log(`  ${status.padEnd(14)} ${row.label.padEnd(24)} ${row.ratio.toFixed(2)}:1  (>= ${row.threshold}:1)`);
    }
  }
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main(): Promise<void> {
  const violations: string[] = [];
  const reportRows: ReportRow[] = [];
  const cssBlocks: string[] = [];
  const swatches: Record<string, Swatch> = { ...SIGNATURE_SWATCHES };

  for (const hueKey of HUE_KEYS) {
    for (const moodKey of MOOD_KEYS) {
      const palette = buildPalette(hueKey, moodKey);
      const t = Object.fromEntries(palette.tokens);

      for (const result of computeContrastResults(t)) {
        reportRows.push({
          key: palette.key,
          label: result.label,
          ratio: result.ratio,
          threshold: result.threshold,
          fatal: result.fatal,
        });
        if (!result.pass && result.fatal) {
          violations.push(
            `${palette.key}: "${result.label}" measured ${result.ratio.toFixed(2)}:1, needed >= ${result.threshold}:1`,
          );
        }
      }

      cssBlocks.push(renderCssBlock(palette.className, palette.tokens));
      swatches[palette.key] = { accent: t.accent, bg: t.bg, card: t.card };
    }
  }

  if (REPORT_MODE) {
    printReport(reportRows);
    return;
  }

  if (violations.length > 0) {
    throw new Error(`Palette contrast assertions failed:\n${violations.join('\n')}`);
  }

  await writeGeneratedCss(cssBlocks);
  await writeGeneratedSwatches(swatches);

  console.log(`Generated ${cssBlocks.length} theme blocks -> ${path.relative(process.cwd(), CSS_OUT)}`);
  console.log(`Generated ${Object.keys(swatches).length} swatches -> ${path.relative(process.cwd(), SWATCH_OUT)}`);
}

main().catch((err: unknown) => {
  console.error(err);
  process.exit(1);
});
