import { NextResponse } from 'next/server';
import { withAuth } from '@/lib/api/with-auth';
import {
  deleteAllUserMeals,
  deleteAllUserMeasurements,
  deleteAllUserCalorieProfiles,
  deleteAllUserOAuthClients,
  deleteAllUserOAuthRefreshTokens,
  deleteAllUserTodos,
  deleteAllUserMcpServers,
  deleteAllUserNotificationPreferences,
  deleteAllUserApiRequestLogs,
  deleteAllUserApiaryTasks,
  deleteAllUserApiaryLogs,
  deleteAllUserApiaryHives,
  deleteAllUserApiaryYards,
  deleteAllUserTripShares,
  deleteAllUserTripDocuments,
  deleteAllUserTripCompanions,
  deleteAllUserTripChecklistItems,
  deleteAllUserTripDays,
  deleteAllUserTripPlaces,
  deleteAllUserTripBookings,
  deleteAllUserTrips,
} from '@my-hub/shared/services';

/**
 * DELETE all data for the authenticated user across every feature.
 * Useful for e2e test cleanup and for the "nuke everything" UI action.
 */
export const POST = withAuth(async ({ user }) => {
  const [
    meals,
    measurements,
    calorieProfiles,
    oauthRefreshTokens,
    mcpClients,
    mcpServers,
    todos,
    notificationPreferences,
    apiRequestLogs,
    apiaryTasks,
    apiaryLogs,
    apiaryHives,
    apiaryYards,
    tripShares,
    tripDocuments,
    tripCompanions,
    tripChecklistItems,
    tripDays,
    tripPlaces,
    tripBookings,
    trips,
  ] = await Promise.all([
    deleteAllUserMeals(user.id),
    deleteAllUserMeasurements(user.id),
    deleteAllUserCalorieProfiles(user.id),
    deleteAllUserOAuthRefreshTokens(user.id),
    deleteAllUserOAuthClients(user.id),
    deleteAllUserTodos(user.id),
    deleteAllUserMcpServers(user.id),
    deleteAllUserNotificationPreferences(user.id),
    deleteAllUserApiRequestLogs(user.id),
    deleteAllUserApiaryTasks(user.id),
    deleteAllUserApiaryLogs(user.id),
    deleteAllUserApiaryHives(user.id),
    deleteAllUserApiaryYards(user.id),
    deleteAllUserTripShares(user.id),
    deleteAllUserTripDocuments(user.id),
    deleteAllUserTripCompanions(user.id),
    deleteAllUserTripChecklistItems(user.id),
    deleteAllUserTripDays(user.id),
    deleteAllUserTripPlaces(user.id),
    deleteAllUserTripBookings(user.id),
    deleteAllUserTrips(user.id),
  ]);

  return NextResponse.json({
    results: {
      meals,
      measurements,
      calorie_profiles: calorieProfiles,
      oauth_refresh_tokens: oauthRefreshTokens,
      oauth_clients: mcpClients,
      mcp_servers: mcpServers,
      todos,
      notification_preferences: notificationPreferences,
      api_request_logs: apiRequestLogs,
      apiary_tasks: apiaryTasks,
      apiary_logs: apiaryLogs,
      apiary_hives: apiaryHives,
      apiary_yards: apiaryYards,
      trip_shares: tripShares,
      trip_documents: tripDocuments,
      trip_companions: tripCompanions,
      trip_checklist_items: tripChecklistItems,
      trip_days: tripDays,
      trip_places: tripPlaces,
      trip_bookings: tripBookings,
      trips,
    },
  });
});
