import { route } from '@/lib/api/route';
import {
  deleteAllUserMeals,
  deleteAllUserMeasurements,
  deleteAllUserCalorieProfiles,
  deleteAllUserOAuthClients,
  deleteAllUserOAuthRefreshTokens,
  deleteAllUserTodos,
  deleteAllUserMcpServers,
  deleteAllUserNotificationPreferences,
  deleteAllUserApiRequestLogs,
  deleteAllUserApiaryTasks,
  deleteAllUserApiaryLogs,
  deleteAllUserApiaryHives,
  deleteAllUserApiaryYards,
  deleteAllUserTripShares,
  deleteAllUserTripDocuments,
  deleteAllUserTripCompanions,
  deleteAllUserTripChecklistItems,
  deleteAllUserTripDays,
  deleteAllUserTripPlaces,
  deleteAllUserTripBookings,
  deleteAllUserTrips,
  deleteAllUserFinanceBudgets,
  deleteAllUserAvailableOverrides,
} from '@my-hub/shared/services';

/**
 * DELETE all data for the authenticated user across every feature.
 * Useful for e2e test cleanup and for the "nuke everything" UI action.
 */
export const POST = route(async ({ user }) => {
  const [
    meals,
    measurements,
    calorieProfiles,
    oauthRefreshTokens,
    mcpClients,
    mcpServers,
    todos,
    notificationPreferences,
    apiRequestLogs,
    apiaryTasks,
    apiaryLogs,
    apiaryHives,
    apiaryYards,
    tripShares,
    tripDocuments,
    tripCompanions,
    tripChecklistItems,
    tripDays,
    tripPlaces,
    tripBookings,
    trips,
    finances,
  ] = await Promise.all([
    deleteAllUserMeals(user.id),
    deleteAllUserMeasurements(user.id),
    deleteAllUserCalorieProfiles(user.id),
    deleteAllUserOAuthRefreshTokens(user.id),
    deleteAllUserOAuthClients(user.id),
    deleteAllUserTodos(user.id),
    deleteAllUserMcpServers(user.id),
    deleteAllUserNotificationPreferences(user.id),
    deleteAllUserApiRequestLogs(user.id),
    deleteAllUserApiaryTasks(user.id),
    deleteAllUserApiaryLogs(user.id),
    deleteAllUserApiaryHives(user.id),
    deleteAllUserApiaryYards(user.id),
    deleteAllUserTripShares(user.id),
    deleteAllUserTripDocuments(user.id),
    deleteAllUserTripCompanions(user.id),
    deleteAllUserTripChecklistItems(user.id),
    deleteAllUserTripDays(user.id),
    deleteAllUserTripPlaces(user.id),
    deleteAllUserTripBookings(user.id),
    deleteAllUserTrips(user.id),
    deleteAllUserFinanceBudgets(user.id),
    deleteAllUserAvailableOverrides(user.id),
  ]);

  return {
    results: {
      meals,
      measurements,
      calorieProfiles,
      oauthRefreshTokens,
      oauthClients: mcpClients,
      mcpServers,
      todos,
      notificationPreferences,
      apiRequestLogs,
      apiaryTasks,
      apiaryLogs,
      apiaryHives,
      apiaryYards,
      tripShares,
      tripDocuments,
      tripCompanions,
      tripChecklistItems,
      tripDays,
      tripPlaces,
      tripBookings,
      trips,
      finances,
    },
  };
});
